version: 2.1

executors:
  linux-executor:
    machine:
      image: ubuntu-2004:current

jobs:
  docker-dev:
    executor: linux-executor
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            docker ls

  docker-latest:
    executor: linux-executor
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            docker ls

workflows:
  CI-CD:
    jobs:
      - docker-dev:
          name: docker:dev
          context: docker-hub
          filters:
            branches:
              only: [ dev ]
      - docker-latest:
          name: docker:latest
          type: approval
          context: docker-hub
          filters:
            branches:
              only: [ master ]